### ISSUE TITLE
Phinx Migration

### ISSUE THREAD

**Issue by adilshahzad** [slimphp/Tutorial-First-Application#5]
On Windows 7 professional the command `php vendor/bin/phinx migrate` doesn't work, try it without php will run the migration successfully.

**Comment by delroh** [comment]
Also, it doesn't say you have to install phinx since slim doesn't include it already.

**Comment by adilshahzad** [comment]
@delroh it's already there, if you are using composer than it'll be installed. You can see it inside the compser.json file inside the src/ directory.

**Comment by delroh** [comment]
You're right. After all the confusion, turns out I installed a different project via composer and that was the reason phinx was not there. My apologies. Thank you!

**Comment by karolsenami** [comment]
It doesn't work neither on my Mac, tryed multiple things but guess I'm missing something. I tryed using Phinx along but it didn't work.
I commented on [this issue](https://github.com/robmorgan/phinx/issues/387) on the Phinx repository 

Edit:
Found my solution : the problem was that I forgot to start MySQL server ! (I'm totally new to back-end and I feel stupid I didn't think about it). Hope someone else won't get stuck as I've been !

**Comment by goldsky** [comment]
`vendor/bin/phinx` requires `__DIR__ . '/../app/phinx.php'` which doesn't exist

**Comment by glewe** [comment]
In my case, Windows 10, I had to install phinx first, running
`composer require robmorgan/phinx`
After that I had to run this to migrate (note, you have to use backslashes in Windows)
`vendor\bin\phinx migrate`

**Comment by chroda** [comment]
Guys, after some trouble, I did with this:
`php vendor/robmorgan/phinx/bin/phinx migrate`

- You need to use this inside src folder, after instaled your dependencies.
- I use windows 10 here with ConEmu & git-bash, so my path its ok in this way.

Good luck and study everyone. 😄
